- id: format
  name: format code
  description: format solidity code with `forge fmt`
  language: system
  entry: forge fmt
  pass_filenames: false
- id: snapshot
  name: take gas snapshot
  description: generate gas snapshot report with `forge snapshot`
  language: system
  entry: forge snapshot
  pass_filenames: false
